### ISSUE TITLE
Doesnt work on PSTV

### ISSUE THREAD

**Issue by SilicaAndPina** [SilicaAndPina/Firmware-Reinstall#1]
For some people it says "This Software Cannot Be Used With This System"
Apparently this can be gotten around by spoofing your firmware to a version lower than 3.60, in HENKAKU Settings

**Comment by Gnarmagon** [comment]
My Original PSVita shows the same Error.

**Comment by Gnarmagon** [comment]
I tested it a bit and I think it's related to the System Software.....
Do you have a working Version of the App ? (you could "dump" the Folder and inject it before installing)

**Comment by SilicaAndPina** [comment]
Try spoofing the version to 1.00 >_>

**Comment by Gnarmagon** [comment]
You mean with Henkaku ?

**Comment by Gnarmagon** [comment]
Nevermind

**Comment by SilicaAndPina** [comment]
SOLVED: This is caused because you are spoofing 3.65 or 3.63 in HENKAKU Settings. try spoofing a version lower than 3.60, or disabling version spoofing >_>
